### ISSUE TITLE
de translation for "SIGN_UP_HAVE_ACCOUNT_TEXT"

### ISSUE THREAD

**Issue by royAmmerschuber** [Locale/amplify-i18n#7]
german translation for  `"SIGN_UP_HAVE_ACCOUNT_TEXT"` is terrible. it should be more something like `"Haben sie ein Konto?"` or `"Haben sie bereits ein Konto?"`

**Comment by thibaultdalban** [comment]
@royAmmerschuber sorry I missed your issue 😔

Closed by #9

**Comment by thibaultdalban** [comment]
Released => `amplify-i18n@0.4.0`
